with Ada.Strings.Unbounded; use Ada.Strings.Unbounded;

package body Definitions is

   function "+" (S : String) return Unbounded_String
     renames To_Unbounded_String;

   function All_Snippets return Snippet_Array is
   begin
      return Snippet_Array'
        (1 =>
           (Prefix      => +"proc",
            Body        => +"procedure ${1:Name} is\n  ${2}\nbegin\n  ${3:-- body}\nend ${1:Name};",
            Description => +"procedure body",
            Standards   => All_Standards,
            With_Units  => +""),
         2 =>
           (Prefix      => +"procs",
            Body        => +"procedure ${1:Name} (${2:Param} : ${3:Type});",
            Description => +"procedure specification (declaration)",
            Standards   => All_Standards,
            With_Units  => +""),
         3 =>
           (Prefix      => +"func",
            Body        => +"function ${1:Name} (${2:Param} : ${3:Type}) return ${4:Return_Type}\n  ${5}\nbegin\n  ${6:-- body}\nend ${1:Name};",
            Description => +"function body",
            Standards   => All_Standards,
            With_Units  => +""),
         4 =>
           (Prefix      => +"funcs",
            Body        => +"function ${1:Name} (${2:Param} : ${3:Type}) return ${4:Return_Type};",
            Description => +"function specification (declaration)",
            Standards   => All_Standards,
            With_Units  => +""),
         5 =>
           (Prefix      => +"pkg",
            Body        => +"package ${1:Name} is\n  ${2}\nend ${1:Name};",
            Description => +"package specification",
            Standards   => All_Standards,
            With_Units  => +""),
         6 =>
           (Prefix      => +"pkgb",
            Body        => +"package body ${1:Name} is\n  ${2}\nbegin\n  ${3}\nend ${1:Name};",
            Description => +"package body",
            Standards   => All_Standards,
            With_Units  => +""),
         7 =>
           (Prefix      => +"task",
            Body        => +"task ${1:Name} is\n  ${2:-- entries}\nend ${1:Name};",
            Description => +"task specification",
            Standards   => Ravenscar_Compat,
            With_Units  => +""),
         8 =>
           (Prefix      => +"taskb",
            Body        => +"task body ${1:Name} is\n  ${2}\nbegin\n  ${3:-- body}\nend ${1:Name};",
            Description => +"task body",
            Standards   => Ravenscar_Compat,
            With_Units  => +""),
         9 =>
           (Prefix      => +"prot",
            Body        => +"protected ${1:Name} is\n  ${2:-- operations}\nend ${1:Name};",
            Description => +"protected object specification",
            Standards   => All_Standards,
            With_Units  => +""),
         10 =>
           (Prefix      => +"protb",
            Body        => +"protected body ${1:Name} is\n  ${2}\nbegin\n  ${3}\nend ${1:Name};",
            Description => +"protected object body",
            Standards   => All_Standards,
            With_Units  => +""),
         11 =>
           (Prefix      => +"with",
            Body        => +"with ${1:Unit};",
            Description => +"with clause",
            Standards   => All_Standards,
            With_Units  => +""),
         12 =>
           (Prefix      => +"use",
            Body        => +"use ${1:Unit};",
            Description => +"use clause",
            Standards   => All_Standards,
            With_Units  => +""),
         13 =>
           (Prefix      => +"if",
            Body        => +"if ${1:Condition} then\n  ${2}\nend if;",
            Description => +"if statement",
            Standards   => All_Standards,
            With_Units  => +""),
         14 =>
           (Prefix      => +"ife",
            Body        => +"if ${1:Condition} then\n  ${2}\nelse\n  ${3}\nend if;",
            Description => +"if/else statement",
            Standards   => All_Standards,
            With_Units  => +""),
         15 =>
           (Prefix      => +"case",
            Body        => +"case ${1:Expression} is\n  when ${2:Choice} =>\n    ${3}\nend case;",
            Description => +"case statement",
            Standards   => All_Standards,
            With_Units  => +""),
         16 =>
           (Prefix      => +"loop",
            Body        => +"loop\n  ${1}\nend loop;",
            Description => +"basic loop",
            Standards   => All_Standards,
            With_Units  => +""),
         17 =>
           (Prefix      => +"for",
            Body        => +"for ${1:Var} in ${2:Range} loop\n  ${3}\nend loop;",
            Description => +"for loop",
            Standards   => All_Standards,
            With_Units  => +""),
         18 =>
           (Prefix      => +"while",
            Body        => +"while ${1:Condition} loop\n  ${2}\nend loop;",
            Description => +"while loop",
            Standards   => All_Standards,
            With_Units  => +""),
         19 =>
           (Prefix      => +"type",
            Body        => +"type ${1:Name} is ${2:definition};",
            Description => +"type declaration",
            Standards   => All_Standards,
            With_Units  => +""),
         20 =>
           (Prefix      => +"rec",
            Body        => +"type ${1:Name} is record\n  ${2:Field} : ${3:Type};\nend record;",
            Description => +"record type",
            Standards   => All_Standards,
            With_Units  => +""),
         21 =>
           (Prefix      => +"arr",
            Body        => +"type ${1:Name} is array (${2:Index}) of ${3:Component_Type};",
            Description => +"array type",
            Standards   => All_Standards,
            With_Units  => +""),
         22 =>
           (Prefix      => +"var",
            Body        => +"${1:Name} : ${2:Type}${3: := ${4:Default}};",
            Description => +"variable declaration",
            Standards   => All_Standards,
            With_Units  => +""),
         23 =>
           (Prefix      => +"const",
            Body        => +"${1:Name} : constant ${2:Type} := ${3:Value};",
            Description => +"constant declaration",
            Standards   => All_Standards,
            With_Units  => +""),
         24 =>
           (Prefix      => +"putl",
            Body        => +"Ada.Text_IO.Put_Line (${1:Item});",
            Description => +"Put_Line statement",
            Standards   => No_Ravenscar,
            With_Units  => +"Ada.Text_IO"),
         25 =>
           (Prefix      => +"put",
            Body        => +"Ada.Text_IO.Put (${1:Item});",
            Description => +"Put statement",
            Standards   => No_Ravenscar,
            With_Units  => +"Ada.Text_IO"),
         26 =>
           (Prefix      => +"getl",
            Body        => +"Ada.Text_IO.Get_Line (${1:Item});",
            Description => +"Get_Line statement",
            Standards   => No_Ravenscar,
            With_Units  => +"Ada.Text_IO"),
         27 =>
           (Prefix      => +"gen",
            Body        => +"generic\n  type ${1:Formal} is private;\npackage ${2:Name} is\n  ${3}\nend ${2:Name};",
            Description => +"generic package specification",
            Standards   => All_Standards,
            With_Units  => +""),
         28 =>
           (Prefix      => +"pragma",
            Body        => +"pragma ${1:Name} (${2:Args});",
            Description => +"pragma line",
            Standards   => All_Standards,
            With_Units  => +""),
         29 =>
           (Prefix      => +"subp",
            Body        => +"${1:procedure | function} ${2:Name} (${3:Param} : ${4:Type})${5: return ${6:Return_Type}};",
            Description => +"subprogram declaration",
            Standards   => All_Standards,
            With_Units  => +""),
         30 =>
           (Prefix      => +"declare",
            Body        => +"declare\n  ${1:-- declarations}\nbegin\n  ${2:-- body}\nend;",
            Description => +"declare block",
            Standards   => All_Standards,
            With_Units  => +""),
         31 =>
           (Prefix      => +"except",
            Body        => +"exception\n  when ${1:Error} =>\n    ${2}",
            Description => +"exception handler",
            Standards   => All_Standards,
            With_Units  => +""),
         32 =>
           (Prefix      => +"req",
            Body        => +"  ${1:Precondition};",
            Description => +"SPARK precondition aspect",
            Standards   => Spark_All,
            With_Units  => +""),
         33 =>
           (Prefix      => +"ens",
            Body        => +"  ${1:Postcondition};",
            Description => +"SPARK postcondition aspect",
            Standards   => Spark_All,
            With_Units  => +""),
         34 =>
           (Prefix      => +"par",
            Body        => +"parallel for ${1:Var} in ${2:Range} loop\n  ${3}\nend loop;",
            Description => +"parallel for loop (Ada 2022)",
            Standards   => Ada_2022_Only,
            With_Units  => +""),
         35 =>
           (Prefix      => +"parb",
            Body        => +"parallel\n  ${1:-- parallel statements}\nend parallel;",
            Description => +"parallel block (Ada 2022)",
            Standards   => Ada_2022_Only,
            With_Units  => +""),
         36 =>
           (Prefix      => +"subtype",
            Body        => +"subtype ${1:Name} is ${2:Base_Type} range ${3:Limit};",
            Description => +"subtype declaration",
            Standards   => All_Standards,
            With_Units  => +""),
         37 =>
           (Prefix      => +"enum",
            Body        => +"type ${1:Name} is (${2:Element_1}, ${3:Element_2});",
            Description => +"enumeration type",
            Standards   => All_Standards,
            With_Units  => +""),
         38 =>
           (Prefix      => +"access",
            Body        => +"type ${1:Name} is access ${2:Target_Type};",
            Description => +"access type",
            Standards   => All_Standards,
            With_Units  => +""),
         39 =>
           (Prefix      => +"delta",
            Body        => +"type ${1:Name} is delta ${2:Delta} range ${3:Low} .. ${4:High};",
            Description => +"fixed-point type",
            Standards   => All_Standards,
            With_Units  => +""),
         40 =>
           (Prefix      => +"digits",
            Body        => +"type ${1:Name} is digits ${2:D} range ${3:Low} .. ${4:High};",
            Description => +"floating-point type",
            Standards   => All_Standards,
            With_Units  => +""),
         41 =>
           (Prefix      => +"ren",
            Body        => +"${1:Name} : ${2:Type} renames ${3:Original};",
            Description => +"renames declaration",
            Standards   => All_Standards,
            With_Units  => +""),
         42 =>
           (Prefix      => +"separate",
            Body        => +"separate (${1:Parent})\n  ${2}",
            Description => +"separate body stub",
            Standards   => All_Standards,
            With_Units  => +""),
         43 =>
           (Prefix      => +"elab",
            Body        => +"pragma Elaborate (${1:Unit});",
            Description => +"pragma Elaborate",
            Standards   => All_Standards,
            With_Units  => +""),
         44 =>
           (Prefix      => +"ravenscar",
            Body        => +"pragma Profile (Ravenscar);",
            Description => +"Ravenscar profile pragma",
            Standards   => Ravenscar_Only,
            With_Units  => +""),
         45 =>
           (Prefix      => +"jorvik",
            Body        => +"pragma Profile (Jorvik);",
            Description => +"Jorvik profile pragma",
            Standards   => Jorvik_Only,
            With_Units  => +""),
         46 =>
           (Prefix      => +"use_type",
            Body        => +"use type ${1:Type};",
            Description => +"use type clause",
            Standards   => All_Standards,
            With_Units  => +""),
         47 =>
           (Prefix      => +"pragma_import",
            Body        => +"pragma Import (${1:Convention}, ${2:Entity}, ${3:\"External_Name\"});",
            Description => +"pragma Import",
            Standards   => All_Standards,
            With_Units  => +""),
         48 =>
           (Prefix      => +"pragma_assert",
            Body        => +"pragma Assert (${1:Condition});",
            Description => +"pragma Assert",
            Standards   => All_Standards,
            With_Units  => +""));
   end All_Snippets;

end Definitions;
