with Ada.Strings.Unbounded; use Ada.Strings.Unbounded;

package body Definitions is

   function "+" (S : String) return Unbounded_String
     renames To_Unbounded_String;

   function All_Snippets return Snippet_Array is
   begin
      return Snippet_Array'
        (1 =>
           (Prefix      => +"proc",
             Body_Str    => +"procedure ${1:Name} is\n  ${2}\nbegin\n  ${3:-- body}\nend ${1:Name};",
            Description => +"procedure body",
            Standards   => All_Standards,
            With_Units  => +""),
         2 =>
           (Prefix      => +"procs",
             Body_Str    => +"procedure ${1:Name} (${2:Param} : ${3:Type});",
            Description => +"procedure specification (declaration)",
            Standards   => All_Standards,
            With_Units  => +""),
         3 =>
           (Prefix      => +"func",
             Body_Str    => +"function ${1:Name} (${2:Param} : ${3:Type}) return ${4:Return_Type}\n  ${5}\nbegin\n  ${6:-- body}\nend ${1:Name};",
            Description => +"function body",
            Standards   => All_Standards,
            With_Units  => +""),
         4 =>
           (Prefix      => +"funcs",
             Body_Str    => +"function ${1:Name} (${2:Param} : ${3:Type}) return ${4:Return_Type};",
            Description => +"function specification (declaration)",
            Standards   => All_Standards,
            With_Units  => +""),
         5 =>
           (Prefix      => +"pkg",
             Body_Str    => +"package ${1:Name} is\n  ${2}\nend ${1:Name};",
            Description => +"package specification",
            Standards   => All_Standards,
            With_Units  => +""),
         6 =>
           (Prefix      => +"pkgb",
             Body_Str    => +"package body ${1:Name} is\n  ${2}\nbegin\n  ${3}\nend ${1:Name};",
            Description => +"package body",
            Standards   => All_Standards,
            With_Units  => +""),
         7 =>
           (Prefix      => +"task",
             Body_Str    => +"task ${1:Name} is\n  ${2:-- entries}\nend ${1:Name};",
            Description => +"task specification",
            Standards   => Ravenscar_Compat,
            With_Units  => +""),
         8 =>
           (Prefix      => +"taskb",
             Body_Str    => +"task body ${1:Name} is\n  ${2}\nbegin\n  ${3:-- body}\nend ${1:Name};",
            Description => +"task body",
            Standards   => Ravenscar_Compat,
            With_Units  => +""),
         9 =>
           (Prefix      => +"prot",
             Body_Str    => +"protected ${1:Name} is\n  ${2:-- operations}\nend ${1:Name};",
            Description => +"protected object specification",
            Standards   => All_Standards,
            With_Units  => +""),
         10 =>
           (Prefix      => +"protb",
             Body_Str    => +"protected body ${1:Name} is\n  ${2}\nbegin\n  ${3}\nend ${1:Name};",
            Description => +"protected object body",
            Standards   => All_Standards,
            With_Units  => +""),
         11 =>
           (Prefix      => +"with",
             Body_Str    => +"with ${1:Unit};",
            Description => +"with clause",
            Standards   => All_Standards,
            With_Units  => +""),
         12 =>
           (Prefix      => +"use",
             Body_Str    => +"use ${1:Unit};",
            Description => +"use clause",
            Standards   => All_Standards,
            With_Units  => +""),
         13 =>
           (Prefix      => +"if",
             Body_Str    => +"if ${1:Condition} then\n  ${2}\nend if;",
            Description => +"if statement",
            Standards   => All_Standards,
            With_Units  => +""),
         14 =>
           (Prefix      => +"ife",
             Body_Str    => +"if ${1:Condition} then\n  ${2}\nelse\n  ${3}\nend if;",
            Description => +"if/else statement",
            Standards   => All_Standards,
            With_Units  => +""),
         15 =>
           (Prefix      => +"case",
             Body_Str    => +"case ${1:Expression} is\n  when ${2:Choice} =>\n    ${3}\nend case;",
            Description => +"case statement",
            Standards   => All_Standards,
            With_Units  => +""),
         16 =>
           (Prefix      => +"loop",
             Body_Str    => +"loop\n  ${1}\nend loop;",
            Description => +"basic loop",
            Standards   => All_Standards,
            With_Units  => +""),
         17 =>
           (Prefix      => +"for",
             Body_Str    => +"for ${1:Var} in ${2:Range} loop\n  ${3}\nend loop;",
            Description => +"for loop",
            Standards   => All_Standards,
            With_Units  => +""),
         18 =>
           (Prefix      => +"while",
             Body_Str    => +"while ${1:Condition} loop\n  ${2}\nend loop;",
            Description => +"while loop",
            Standards   => All_Standards,
            With_Units  => +""),
         19 =>
           (Prefix      => +"type",
             Body_Str    => +"type ${1:Name} is ${2:definition};",
            Description => +"type declaration",
            Standards   => All_Standards,
            With_Units  => +""),
         20 =>
           (Prefix      => +"rec",
             Body_Str    => +"type ${1:Name} is record\n  ${2:Field} : ${3:Type};\nend record;",
            Description => +"record type",
            Standards   => All_Standards,
            With_Units  => +""),
         21 =>
           (Prefix      => +"arr",
             Body_Str    => +"type ${1:Name} is array (${2:Index}) of ${3:Component_Type};",
            Description => +"array type",
            Standards   => All_Standards,
            With_Units  => +""),
         22 =>
           (Prefix      => +"var",
             Body_Str    => +"${1:Name} : ${2:Type}${3: := ${4:Default}};",
            Description => +"variable declaration",
            Standards   => All_Standards,
            With_Units  => +""),
         23 =>
           (Prefix      => +"const",
             Body_Str    => +"${1:Name} : constant ${2:Type} := ${3:Value};",
            Description => +"constant declaration",
            Standards   => All_Standards,
            With_Units  => +""),
         24 =>
           (Prefix      => +"putl",
             Body_Str    => +"Ada.Text_IO.Put_Line (${1:Item});",
            Description => +"Put_Line statement",
            Standards   => No_Ravenscar,
            With_Units  => +"Ada.Text_IO"),
         25 =>
           (Prefix      => +"put",
             Body_Str    => +"Ada.Text_IO.Put (${1:Item});",
            Description => +"Put statement",
            Standards   => No_Ravenscar,
            With_Units  => +"Ada.Text_IO"),
         26 =>
           (Prefix      => +"getl",
             Body_Str    => +"Ada.Text_IO.Get_Line (${1:Item});",
            Description => +"Get_Line statement",
            Standards   => No_Ravenscar,
            With_Units  => +"Ada.Text_IO"),
         27 =>
           (Prefix      => +"gen",
             Body_Str    => +"generic\n  type ${1:Formal} is private;\npackage ${2:Name} is\n  ${3}\nend ${2:Name};",
            Description => +"generic package specification",
            Standards   => All_Standards,
            With_Units  => +""),
         28 =>
           (Prefix      => +"pragma",
             Body_Str    => +"pragma ${1:Name} (${2:Args});",
            Description => +"pragma line",
            Standards   => All_Standards,
            With_Units  => +""),
         29 =>
           (Prefix      => +"subp",
             Body_Str    => +"${1:procedure | function} ${2:Name} (${3:Param} : ${4:Type})${5: return ${6:Return_Type}};",
            Description => +"subprogram declaration",
            Standards   => All_Standards,
            With_Units  => +""),
         30 =>
           (Prefix      => +"declare",
             Body_Str    => +"declare\n  ${1:-- declarations}\nbegin\n  ${2:-- body}\nend;",
            Description => +"declare block",
            Standards   => All_Standards,
            With_Units  => +""),
         31 =>
           (Prefix      => +"except",
             Body_Str    => +"exception\n  when ${1:Error} =>\n    ${2}",
            Description => +"exception handler",
            Standards   => All_Standards,
            With_Units  => +""),
          32 =>
            (Prefix      => +"precondition",
             Body_Str    => +"  Precondition => ${1:Condition};",
             Description => +"Precondition aspect",
             Standards   => Ada_2012_And_Spark,
             With_Units  => +""),
          33 =>
            (Prefix      => +"postcondition",
             Body_Str    => +"  Postcondition => ${1:Condition};",
             Description => +"Postcondition aspect",
             Standards   => Ada_2012_And_Spark,
             With_Units  => +""),
         34 =>
           (Prefix      => +"par",
             Body_Str    => +"parallel for ${1:Var} in ${2:Range} loop\n  ${3}\nend loop;",
            Description => +"parallel for loop (Ada 2022)",
            Standards   => Ada_2022_Only,
            With_Units  => +""),
         35 =>
           (Prefix      => +"parb",
             Body_Str    => +"parallel\n  ${1:-- parallel statements}\nend parallel;",
            Description => +"parallel block (Ada 2022)",
            Standards   => Ada_2022_Only,
            With_Units  => +""),
         36 =>
           (Prefix      => +"subtype",
             Body_Str    => +"subtype ${1:Name} is ${2:Base_Type} range ${3:Limit};",
            Description => +"subtype declaration",
            Standards   => All_Standards,
            With_Units  => +""),
         37 =>
           (Prefix      => +"enum",
             Body_Str    => +"type ${1:Name} is (${2:Element_1}, ${3:Element_2});",
            Description => +"enumeration type",
            Standards   => All_Standards,
            With_Units  => +""),
         38 =>
           (Prefix      => +"access",
             Body_Str    => +"type ${1:Name} is access ${2:Target_Type};",
            Description => +"access type",
            Standards   => All_Standards,
            With_Units  => +""),
         39 =>
           (Prefix      => +"delta",
             Body_Str    => +"type ${1:Name} is delta ${2:Delta} range ${3:Low} .. ${4:High};",
            Description => +"fixed-point type",
            Standards   => All_Standards,
            With_Units  => +""),
         40 =>
           (Prefix      => +"digits",
             Body_Str    => +"type ${1:Name} is digits ${2:D} range ${3:Low} .. ${4:High};",
            Description => +"floating-point type",
            Standards   => All_Standards,
            With_Units  => +""),
         41 =>
           (Prefix      => +"ren",
             Body_Str    => +"${1:Name} : ${2:Type} renames ${3:Original};",
            Description => +"renames declaration",
            Standards   => All_Standards,
            With_Units  => +""),
         42 =>
           (Prefix      => +"separate",
             Body_Str    => +"separate (${1:Parent})\n  ${2}",
            Description => +"separate body stub",
            Standards   => All_Standards,
            With_Units  => +""),
         43 =>
           (Prefix      => +"elab",
             Body_Str    => +"pragma Elaborate (${1:Unit});",
            Description => +"pragma Elaborate",
            Standards   => All_Standards,
            With_Units  => +""),
         44 =>
           (Prefix      => +"ravenscar",
             Body_Str    => +"pragma Profile (Ravenscar);",
            Description => +"Ravenscar profile pragma",
            Standards   => Ravenscar_Only,
            With_Units  => +""),
         45 =>
           (Prefix      => +"jorvik",
             Body_Str    => +"pragma Profile (Jorvik);",
            Description => +"Jorvik profile pragma",
            Standards   => Jorvik_Only,
            With_Units  => +""),
         46 =>
           (Prefix      => +"use_type",
             Body_Str    => +"use type ${1:Type};",
            Description => +"use type clause",
            Standards   => All_Standards,
            With_Units  => +""),
         47 =>
           (Prefix      => +"pragma_import",
             Body_Str    => +"pragma Import (${1:Convention}, ${2:Entity}, ${3:""External_Name""});",
            Description => +"pragma Import",
            Standards   => All_Standards,
            With_Units  => +""),
          48 =>
            (Prefix      => +"pragma_assert",
             Body_Str    => +"pragma Assert (${1:Condition});",
             Description => +"pragma Assert",
             Standards   => All_Standards,
             With_Units  => +""),
          --  Contract aspects (SPARK flow analysis)
          49 =>
            (Prefix      => +"depends",
             Body_Str    => +"  Depends => (${1:Output} => ${2:Input});",
             Description => +"Depends aspect",
             Standards   => Spark_All,
             With_Units  => +""),
          50 =>
            (Prefix      => +"global",
             Body_Str    => +"  Global => (${1:In} => ${2:Var});",
             Description => +"Global aspect",
             Standards   => Spark_All,
             With_Units  => +""),
          51 =>
            (Prefix      => +"refined_state",
             Body_Str    => +"  Refined_State => (${1:State} => (${2:Concrete}));",
             Description => +"Refined_State aspect",
             Standards   => Spark_All,
             With_Units  => +""),
          52 =>
            (Prefix      => +"refined_depends",
             Body_Str    => +"  Refined_Depends => (${1:Output} => ${2:Input});",
             Description => +"Refined_Depends aspect",
             Standards   => Spark_All,
             With_Units  => +""),
          53 =>
            (Prefix      => +"refined_global",
             Body_Str    => +"  Refined_Global => (${1:In} => ${2:Var});",
             Description => +"Refined_Global aspect",
             Standards   => Spark_All,
             With_Units  => +""),
          54 =>
            (Prefix      => +"proof_in",
             Body_Str    => +"  Proof_In => (${1:Var});",
             Description => +"Proof_In aspect",
             Standards   => Spark_All,
             With_Units  => +""),
          55 =>
            (Prefix      => +"proof_out",
             Body_Str    => +"  Proof_Out => (${1:Var});",
             Description => +"Proof_Out aspect",
             Standards   => Spark_All,
             With_Units  => +""),
          --  Behavioral contract aspects
          56 =>
            (Prefix      => +"contract_cases",
             Body_Str    => +"  Contract_Cases => (${1:Condition} => ${2:Post}, others => ${3:Post});",
             Description => +"Contract_Cases aspect",
             Standards   => Ada_2012_And_Spark,
             With_Units  => +""),
          57 =>
            (Prefix      => +"exceptional_cases",
             Body_Str    => +"  Exceptional_Cases => (${1:Exception} => ${2:Postcondition});",
             Description => +"Exceptional_Cases aspect",
             Standards   => Ada_2022_And_Spark,
             With_Units  => +""),
          58 =>
            (Prefix      => +"always_terminates",
             Body_Str    => +"  Always_Terminates => ${1:True};",
             Description => +"Always_Terminates aspect",
             Standards   => Ada_2022_And_Spark,
             With_Units  => +""),
          59 =>
            (Prefix      => +"subprogram_variant",
             Body_Str    => +"  Subprogram_Variant => (${1:Decreases} => ${2:Expression});",
             Description => +"Subprogram_Variant aspect",
             Standards   => Ada_2022_And_Spark,
             With_Units  => +""),
          --  Loop annotations
          60 =>
            (Prefix      => +"loop_invariant",
             Body_Str    => +"pragma Loop_Invariant (${1:Condition});",
             Description => +"pragma Loop_Invariant",
             Standards   => Spark_All,
             With_Units  => +""),
          61 =>
            (Prefix      => +"loop_variant",
             Body_Str    => +"pragma Loop_Variant (${1:Decreases} => ${2:Expression});",
             Description => +"pragma Loop_Variant",
             Standards   => Spark_All,
             With_Units  => +""),
          --  SPARK assertion pragmas
          62 =>
            (Prefix      => +"pragma_assume",
             Body_Str    => +"pragma Assume (${1:Condition});",
             Description => +"pragma Assume",
             Standards   => Spark_All,
             With_Units  => +""),
          63 =>
            (Prefix      => +"pragma_annotate",
             Body_Str    => +"pragma Annotate (${1:Check}, ${2:Proof}, ${3:Message});",
             Description => +"pragma Annotate",
             Standards   => Spark_All,
             With_Units  => +""),
          64 =>
            (Prefix      => +"pragma_check",
             Body_Str    => +"pragma Check (${1:Name}, ${2:Condition});",
             Description => +"pragma Check",
             Standards   => Spark_All,
             With_Units  => +""),
          --  Ghost constructs
          65 =>
            (Prefix      => +"ghost_procedure",
             Body_Str    => +"procedure ${1:Name} (${2:Param} : ${3:Type}) with Ghost is\n  ${4}\nbegin\n  ${5:-- body}\nend ${1:Name};",
             Description => +"Ghost procedure body",
             Standards   => Spark_All,
             With_Units  => +""),
          66 =>
            (Prefix      => +"ghost_function",
             Body_Str    => +"function ${1:Name} (${2:Param} : ${3:Type}) return ${4:Return_Type} with Ghost is\n  ${5}\nbegin\n  ${6:-- body}\nend ${1:Name};",
             Description => +"Ghost function body",
             Standards   => Spark_All,
             With_Units  => +""),
          67 =>
            (Prefix      => +"ghost_type",
             Body_Str    => +"type ${1:Name} is ${2:definition} with Ghost;",
             Description => +"Ghost type",
             Standards   => Spark_All,
             With_Units  => +""),
          68 =>
            (Prefix      => +"ghost_package",
             Body_Str    => +"package ${1:Name} is with Ghost\n  ${2}\nend ${1:Name};",
             Description => +"Ghost package specification",
             Standards   => Spark_All,
             With_Units  => +""),
          --  Type predicates and invariants
          69 =>
            (Prefix      => +"type_invariant",
             Body_Str    => +"  Type_Invariant => ${1:Condition};",
             Description => +"Type_Invariant aspect",
             Standards   => Ada_2012_And_Spark,
             With_Units  => +""),
          70 =>
            (Prefix      => +"predicate",
             Body_Str    => +"  Predicate => ${1:Condition};",
             Description => +"Predicate aspect",
             Standards   => Ada_2012_And_Spark,
             With_Units  => +""),
          71 =>
            (Prefix      => +"dynamic_predicate",
             Body_Str    => +"  Dynamic_Predicate => ${1:Condition};",
             Description => +"Dynamic_Predicate aspect",
             Standards   => Ada_2012_And_Spark,
             With_Units  => +""),
          --  Assertion policy
          72 =>
            (Prefix      => +"pragma_assertion_policy",
             Body_Str    => +"pragma Assertion_Policy (${1:Check});",
             Description => +"pragma Assertion_Policy",
             Standards   => Ada_2012_And_Spark,
             With_Units  => +""),
          --  SPARK Mode
          73 =>
            (Prefix      => +"pragma_spark_mode",
             Body_Str    => +"pragma SPARK_Mode (${1:On});",
             Description => +"pragma SPARK_Mode",
             Standards   => Spark_All,
             With_Units  => +""),
          74 =>
            (Prefix      => +"spark_mode",
             Body_Str    => +"  SPARK_Mode => ${1:On};",
             Description => +"SPARK_Mode aspect",
             Standards   => Spark_All,
             With_Units  => +""));
    end All_Snippets;

end Definitions;
